export const ProductsTest = [
    {
        id: 1,
        avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
        productName: "Duke 350",
        qrcode: "Duke 350",
        price: "100",
        itemsLeft: 30,
        statusId: 1,
        approvalId: 1,
        stockSold: 20,
        totalNumber: 50,
        threshold: 10,
        upcomingAmount: 3000,
        userName: "Sonu",
        customerName: "Sonu Suda, arivikunnam P.O Kundannur",
        numberOfOrders: 2,
    },
    {
        id: 2,
        avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
        productName: "Kaavalam Jettikal",
        qrcode: "Duke 350",
        price: "10",
        itemsLeft: 50,
        statusId: 2,
        approvalId: 3,
        stockSold: 0,
        totalNumber: 50,
        threshold: 10,
        upcomingAmount: 350,
        userName: "Denio",
        customerName: "Sonu Suda, arivikunnam P.O Kundannur",
        numberOfOrders: 2,
    },
    {
        id: 3,
        avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
        productName: "Asameese konandras thailam",
        qrcode: "Duke 350",
        price: "150",
        itemsLeft: 25,
        statusId: 3,
        approvalId: 1,
        stockSold: 25,
        totalNumber: 50,
        threshold: 10,
        upcomingAmount: 3750,
        userName: "Akshay",
        customerName: "Sonu Suda, arivikunnam P.O Kundannur",
        numberOfOrders: 2,
    },
    {
        id: 4,
        avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
        productName: "Sonu",
        qrcode: "Duke 350",
        price: "200",
        itemsLeft: 0,
        statusId: 4,
        approvalId: 2,
        stockSold: 50,
        totalNumber: 50,
        threshold: 10,
        upcomingAmount: 0,
        userName: "Haji Moiz Ladakkuttaa",
        customerName: "Sonu Suda, arivikunnam P.O Kundannur",
        numberOfOrders: 2,
    },
    {
        id: 5,
        avatar: "https://flowbite.com/docs/images/people/profile-picture-2.jpg",
        productName: "Umakanth Coffee",
        qrcode: "Duke 350",
        price: "20",
        itemsLeft: 10,
        statusId: 1,
        approvalId: 2,
        stockSold: 40,
        totalNumber: 50,
        upcomingAmount: 200,
        userName: "Haji Moiz Ladakkuttaa",
        customerName: "Sonu Suda, arivikunnam P.O Kundannur",
        numberOfOrders: 2,
    },
    // Add more comments as needed
];