name: Stage Release

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy_on_stag_server:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Copy files via SSH on Server 1
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.TEST_HOST_1 }}
          username: ${{ secrets.TEST_HOST_1_USERNAME}}
          port: 22
          password: ${{ secrets.TEST_HOST_1_PASSWORD}}
          source: "*"
          target: ${{ secrets.TEST_HOST_1_APPDIR }}/Frontend

      - name: Run commands on Server 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_HOST_1 }}
          username: ${{ secrets.TEST_HOST_1_USERNAME }}
          password: ${{ secrets.TEST_HOST_1_PASSWORD }}
          port: 22
          script: |
            ./deployscript/testing/frontend.sh
